apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        intent: default
    spec:
      nodeClassRef:
        name: default
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      taints:
        - key: dedicated
          value: karpenter
          effect: NoSchedule
      startupTaints:
        - key: startup
          value: pending
          effect: NoSchedule
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.medium", "t3.large"]
      expiration:
        ttlSecondsAfterEmpty: 300
      terminationGracePeriodSeconds: 30
  limits:
    resources:
      cpu: 20
      memory: 200Gi
