apiVersion: v2
name: karpenter
description: Helm chart for deploying AWS Karpenter
type: application
version: 0.1.0
appVersion: "1.3.0"

dependencies:
  - name: karpenter
    version: "1.3.0"
    repository: oci://public.ecr.aws/karpenter
