controller:
  clusterName: my-dev-eks-cluster
  clusterEndpoint: https://your-cluster-endpoint
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::084375583445:role/my-dev-eks-cluster-karpenter-controller-role
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

settings:
  aws:
    interruptionQueueName: my-dev-eks-cluster-karpenter-interruption-queue
